version: '3.3'
services:
  mongodb1:
    image: "mongo:latest"
    container_name: mongodb1
    networks:
      app_subnet:
        ipv4_address: ${IP_PREFIX}.4

  consuldev:
    image: "consul"
    container_name: consuldev
    restart: always
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS: ""
    networks:
      app_subnet:
        ipv4_address: ${IP_PREFIX}.3
    volumes:
      - ./consul.d:/consul/config
    command: 'agent -dev -ui -dns-port 53 -recursor 8.8.8.8 -bind ${IP_PREFIX}.3 -client 0.0.0.0'

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'dimanevelev/tweeter'
    container_name: tweetersrv
    ports:
      - 8080:8080
      - 5005:5005 # remote debug port
    networks:
      - app_subnet
    depends_on:
      - mongodb1
      - consuldev
    dns:
      - ${IP_PREFIX}.3
    environment:
      - 'JAVA_ARGS=${JAVA_ARGS}'

  test:
    image: "azukiapp/dig"
    container_name: test
    stdin_open: true
    tty: true
    restart: on-failure
    command: "tail -f /dev/null"
    networks:
    - app_subnet
  #    depends_on:
  #      - mongodb1
    dns:
     - ${IP_PREFIX}.3

networks:
  app_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${IP_PREFIX}.0/24



